# ansible/roles/monitoring/defaults/main.yml
---
monitoring_namespace: monitoring
prometheus_release_name: kube-prometheus-stack
k8s_local_dir: "{{ playbook_dir }}/../../k8s"
k8s_remote_dir: "/root/k8s"