[control_plane]
k8s-cp ansible_host=172.233.214.152

[workers]
k8s-worker-1 ansible_host=172.232.6.94

# Convenience group so "common" tasks can target every node at once.
[k8s_cluster:children]
control_plane
workers

[k8s_cluster:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
