apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: java-mysql
spec:  
  selector:
      app: java-app
  ports:
    - port: 80 # externally
      targetPort: 8080 # on the container