apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app
  namespace: java-mysql
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: java-app
  endpoints:
    - port: metrics
      path: /actuator/prometheus