---
k8s_version: "1.32"
local_path_version: "v0.0.30" # PVC driver

# Cluster networking
pod_network_cidr: "10.244.0.0/16"   # must match Flannel's default
flannel_manifest_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
kubeconfig: "/etc/kubernetes/admin.conf"

app_namespace: "java-mysql"
java_image: "leandromileski/java-mysql-app:1.0.0"
app_host: "java.{{ hostvars[groups['workers'][0]].ansible_host }}.nip.io"

db_name: "team_app"

